services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    command: -p ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -p ${DB_PORT}' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    restart: always
    environment:
      DB_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
      PORT: ${PORT}
      YT_API_KEY: ${YT_API_KEY}
      YT_CHANNEL_ID: ${YT_CHANNEL_ID}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_TEMPLATE: ${EMAIL_TEMPLATE}
      EMAIL_PUBLIC_KEY: ${EMAIL_PUBLIC_KEY}
      EMAIL_PRIVATE_KEY: ${EMAIL_PRIVATE_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddyfile --adapter caddyfile
    environment:
      PORT: ${PORT}
    depends_on:
      - app

  ddns-updater:
    image: ghcr.io/qdm12/ddns-updater
    container_name: ddns-updater
    ports:
      - 8000:8000/tcp
    volumes:
      - ./updater/data:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_ADDRESS=:8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always

volumes:
  pgdata:
  caddy_data:
  caddy_config: